services:
  #api:
  #  container_name: api_go
  #  build: .
  #  ports:
  #    - 8080:8080
  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=americanas
      - MONGO_INITDB_ROOT_PASSWORD=americanas
    ports:
      - 27017:27017
  redis:
    container_name: redis
    image: redis:3.2
    ports:
      - 6379:6379
